name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.201
      - name: Restore dependencies
        run: |
          cd backend
          dotnet restore
      - name: Test
        run: |
          cd backend
          dotnet test
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: backend
          file: backend/Dockerfile
          tags: mkoveni/assess_backend:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
